#!/usr/bin/env bash

source "$(dirname "$0")/vars"

function usage {
    echo "docker-build is a tool to build elixir project docker image."
    echo ""
    echo "Usage: docker-build"
}

if [ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  usage
fi

set -e

BUILD=`git rev-parse --short HEAD`
TAG="$2"

if [ "$TAG" = "v${APP_VSN}" ]; then
  VERSION_TAG="${DOCKER_ORG}/${SERVICE_NAME}:v${APP_VSN}"
  VERSION_TAG_BUILD="-t ${VERSION_TAG}"
fi

docker build \
    --build-arg MIX_ENV=$MIX_ENV \
    --build-arg APP_NAME=$APP_NAME \
    --build-arg SERVICE_NAME=$SERVICE_NAME \
		--build-arg APP_VSN=$APP_VSN \
		--build-arg GITHUB_SSH_KEY="$GITHUB_SSH_KEY" \
		--build-arg HEX_API_KEY="$HEX_API_KEY" \
		-t ${DOCKER_ORG}/${SERVICE_NAME}:v${APP_VSN}-${BUILD} \
    $VERSION_TAG_BUILD \
		-t ${DOCKER_ORG}/${SERVICE_NAME}:latest .

if [ "$1" = "push" ]; then
  docker push ${DOCKER_ORG}/${SERVICE_NAME}:v${APP_VSN}-${BUILD}
  if [ -n "$VERSION_TAG" ]; then
    docker push $VERSION_TAG
  fi
fi
