#!/usr/bin/env bash

source "$(dirname "$0")/vars"

function usage {
    echo "docker-build is a tool to build elixir project docker image."
    echo ""
    echo "Usage: docker-build [push] [version]"
    echo ""
    echo "push:    Also push the image after successful build."
    echo "version: Exact version to build and push. Usuful for CI. Defaults to current git commit."
    echo ""
    echo "Examples:"
    echo ""
    echo "   docker-build                    - Build the current git commit"
    echo "   docker-build push \$CIRCLE_TAG   - Push and build the image in CI"
    exit
}

if [ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  usage
fi

set -e

BUILD=`git rev-parse --short HEAD`
TAG="$2"

if [ "$TAG" = "v${APP_VSN}" ]; then
  VERSION_TAG="${DOCKER_ORG}/${SERVICE_NAME}:v${APP_VSN}"
  VERSION_TAG_BUILD="-t ${VERSION_TAG}"
fi

docker build \
    --build-arg MIX_ENV=$MIX_ENV \
    --build-arg APP_NAME=$APP_NAME \
    --build-arg SERVICE_NAME=$SERVICE_NAME \
		-t ${DOCKER_ORG}/${SERVICE_NAME}:v${APP_VSN} \
    --file ci.Dockerfile .

if [ "$1" = "push" ]; then
  docker push ${DOCKER_ORG}/${SERVICE_NAME}:v${APP_VSN}
  if [ -n "$VERSION_TAG" ]; then
    docker push $VERSION_TAG
  fi
fi
