#!/usr/bin/env bash

ENV_NAME=${1:-$ENV_NAME}

source "$(dirname "$0")/vars"

ARGS="${@:2}"

echo -e "Getting ${GREEN}${ENV_NAME}${DEF} cluster nodes.."
NODE_IPS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=node:$ECS_CLUSTER-asg" --query 'Reservations[].Instances[].PrivateIpAddress' --output text)

echo -e "${BOLD}==== NODES ====${DEF}"
for IP in $NODE_IPS; do
  echo -e "${YELLOW}$APP_NAME@$IP${DEF}"
done
echo -e "${BOLD}===============${DEF}"

FIRST_IP=$(echo "$NODE_IPS" | awk '{ print $1 }')

echo -e "Getting ${GREEN}${ENV_NAME}${DEF} cookie.."
ERL_COOKIE=${ERL_COOKIE:-$(ssh ec2-user@$FIRST_IP 'docker exec $(docker ps -q -f name=ecs-'$ECS_SERVICE'-) printenv ERL_COOKIE')}

echo "Starting node.."

iex --name $APP_NAME@127.0.0.1 --hidden --cookie "$ERL_COOKIE" $ARGS
