#!/usr/bin/env bash

ENV_NAME=${1:-$ENV_NAME}

source "$(dirname "$0")/vars"

ARGS="${@:2}"

echo -e "Getting ${GREEN}${ENV_NAME}${DEF} cluster nodes.."
NODE_IPS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=node:$ECS_CLUSTER-asg" --query 'Reservations[].Instances[].PrivateIpAddress' --output text)
NODE_COUNT=$(echo -n $(echo $NODE_IPS | wc -w))

if [ "$NODE_COUNT" == "1" ]; then
  echo -e "Getting ${GREEN}${ENV_NAME}${DEF} node $NODE_IPS most recent container logs.."
  ssh -t ec2-user@$NODE_IPS "docker logs \$(docker ps -q -f name=ecs-$ECS_SERVICE- -a | head -n 1) $ARGS"
else
  select NODE in $NODE_IPS; do
    echo -e "Getting ${GREEN}${ENV_NAME}${DEF} node $NODE most recent container logs.."
    ssh -t ec2-user@$NODE "docker logs \$(docker ps -q -f name=ecs-$ECS_SERVICE- -a | head -n 1) $ARGS"
  done
fi
