defmodule MoonWeb.Pages.Assets.IconsPage do
  use MoonWeb, :live_view

  alias Moon.Components.Inline
  alias Moon.Components.CodePreview

  alias Moon.Assets.Icons
  alias Icons.IconAbout
  alias Icons.IconAdd
  alias Icons.IconAlertCircle
  alias Icons.IconAlignLeft
  alias Icons.IconAllSports
  alias Icons.IconArrowDiagonalDownLeft
  alias Icons.IconArrowDiagonalUpRight
  alias Icons.IconArrowDiagonals
  alias Icons.IconArrowDown
  alias Icons.IconArrowLDown
  alias Icons.IconArrowLUp
  alias Icons.IconArrowLeftRight
  alias Icons.IconArrowLeft
  alias Icons.IconArrowRight
  alias Icons.IconArrowTopRight
  alias Icons.IconArrowUpDown
  alias Icons.IconArrowUp
  alias Icons.IconAsianView
  alias Icons.IconAttache
  alias Icons.IconAward
  alias Icons.IconBannerInfo
  alias Icons.IconBell
  alias Icons.IconBitcoinTalk
  alias Icons.IconBombayClub
  alias Icons.IconBurger
  alias Icons.IconCalendarEmpty
  alias Icons.IconCalendar
  alias Icons.IconCard
  alias Icons.IconCase
  alias Icons.IconCashOut
  alias Icons.IconCasinoBell
  alias Icons.IconCasino
  alias Icons.IconChartArea
  alias Icons.IconChartBar
  alias Icons.IconChartPies
  alias Icons.IconChartRound
  alias Icons.IconChartSegment
  alias Icons.IconChevronDownRounded
  alias Icons.IconChevronDown
  alias Icons.IconChevronLeftRounded
  alias Icons.IconChevronLeft
  alias Icons.IconChevronRightRounded
  alias Icons.IconChevronRight
  alias Icons.IconChevronUpDown
  alias Icons.IconChevronUpRounded
  alias Icons.IconChevronUp
  alias Icons.IconCircle
  alias Icons.IconClaps
  alias Icons.IconClock
  alias Icons.IconCloseRounded
  alias Icons.IconCloseSmall
  alias Icons.IconClose
  alias Icons.IconCode
  alias Icons.IconCollapse
  alias Icons.IconCopy
  alias Icons.IconCredit
  alias Icons.IconCrypto
  alias Icons.IconCurrencyArs
  alias Icons.IconCurrencyBdt
  alias Icons.IconCurrencyBob
  alias Icons.IconCurrencyBrl
  alias Icons.IconCurrencyBtc
  alias Icons.IconCurrencyCad
  alias Icons.IconCurrencyClp
  alias Icons.IconCurrencyCny
  alias Icons.IconCurrencyCrc
  alias Icons.IconCurrencyEth
  alias Icons.IconCurrencyEur
  alias Icons.IconCurrencyGel
  alias Icons.IconCurrencyHkd
  alias Icons.IconCurrencyIdr
  alias Icons.IconCurrencyInr
  alias Icons.IconCurrencyIqd
  alias Icons.IconCurrencyJpy
  alias Icons.IconCurrencyKrw
  alias Icons.IconCurrencyLtc
  alias Icons.IconCurrencyMxn
  alias Icons.IconCurrencyMyr
  alias Icons.IconCurrencyPen
  alias Icons.IconCurrencyPkr
  alias Icons.IconCurrencyRub
  alias Icons.IconCurrencySoc
  alias Icons.IconCurrencyThb
  alias Icons.IconCurrencyTrx
  alias Icons.IconCurrencyTry
  alias Icons.IconCurrencyUah
  alias Icons.IconCurrencyUsd
  alias Icons.IconCurrencyUsdt
  alias Icons.IconCurrencyVes
  alias Icons.IconCurrencyVnd
  alias Icons.IconCurrencyXrp
  alias Icons.IconCursor
  alias Icons.IconData
  alias Icons.IconDelete
  alias Icons.IconDesktop
  alias Icons.IconDetails
  alias Icons.IconDouble
  alias Icons.IconDownload
  alias Icons.IconDuotoneArrows
  alias Icons.IconDuotoneChat
  alias Icons.IconDuotoneCoins
  alias Icons.IconDuotoneMail
  alias Icons.IconESportsCallOfDuty
  alias Icons.IconESportsCounterStrike
  alias Icons.IconESportsDota2
  alias Icons.IconESportsENba
  alias Icons.IconESportsESport
  alias Icons.IconESportsFootball
  alias Icons.IconESportsHearthstone
  alias Icons.IconESportsLeagueOfLegends
  alias Icons.IconESportsOverwatch
  alias Icons.IconESportsRainbow
  alias Icons.IconESportsRocketLeague
  alias Icons.IconESportsStarCraft
  alias Icons.IconEdit
  alias Icons.IconErrorCircle
  alias Icons.IconError
  alias Icons.IconExpand
  alias Icons.IconEyeClosed
  alias Icons.IconEye
  alias Icons.IconFacebook
  alias Icons.IconFilter
  alias Icons.IconForward
  alias Icons.IconFreebet
  alias Icons.IconFullScreen
  alias Icons.IconGamepad
  alias Icons.IconGeneralInfo
  alias Icons.IconGift
  alias Icons.IconGlasses
  alias Icons.IconGlobe
  alias Icons.IconGoogleAuth
  alias Icons.IconGoogle
  alias Icons.IconHamburger
  alias Icons.IconHelp
  alias Icons.IconHistory
  alias Icons.IconHome
  alias Icons.IconHub88
  alias Icons.IconHyperlink
  alias Icons.IconInPlay
  alias Icons.IconInfoCircle
  alias Icons.IconInfo
  alias Icons.IconInstagram
  alias Icons.IconLeftArrowCurveRight
  alias Icons.IconLifeRing
  alias Icons.IconLightbulb
  alias Icons.IconLimit
  alias Icons.IconLine
  alias Icons.IconLink
  alias Icons.IconListNumbered
  alias Icons.IconLiveCasino
  alias Icons.IconLiveChat
  alias Icons.IconLiveStream
  alias Icons.IconLock
  alias Icons.IconLogin
  alias Icons.IconLogoPlain
  alias Icons.IconLogout
  alias Icons.IconLoyalty0
  alias Icons.IconMail
  alias Icons.IconMenuHome
  alias Icons.IconMenu
  alias Icons.IconMinus
  alias Icons.IconMobile
  alias Icons.IconMoney
  alias Icons.IconMoneybag
  alias Icons.IconMoon
  alias Icons.IconMore
  alias Icons.IconNews
  alias Icons.IconNotificationUnread
  alias Icons.IconNotification
  alias Icons.IconPadlock
  alias Icons.IconPencil
  alias Icons.IconPhoto
  alias Icons.IconPicture
  alias Icons.IconPin
  alias Icons.IconPlay
  alias Icons.IconPlus
  alias Icons.IconPriceBoost
  alias Icons.IconPrint
  alias Icons.IconProfile
  alias Icons.IconPromotions
  alias Icons.IconRefresh
  alias Icons.IconRow
  alias Icons.IconSbShield
  alias Icons.IconSearch
  alias Icons.IconSettings
  alias Icons.IconShare
  alias Icons.IconSliders
  alias Icons.IconSlots
  alias Icons.IconSnackbarSuccess
  alias Icons.IconSportWidget
  alias Icons.IconSportsAmericanFootBall
  alias Icons.IconSportsBadminton
  alias Icons.IconSportsBaseBall
  alias Icons.IconSportsBasketBall
  alias Icons.IconSportsBiathlon
  alias Icons.IconSportsBoxing
  alias Icons.IconSportsCenter
  alias Icons.IconSportsCricket
  alias Icons.IconSportsCycling
  alias Icons.IconSportsDarts
  alias Icons.IconSportsESports
  alias Icons.IconSportsFantasy
  alias Icons.IconSportsFeatured
  alias Icons.IconSportsFootBall
  alias Icons.IconSportsGolf
  alias Icons.IconSportsGreyhound
  alias Icons.IconSportsHandBall
  alias Icons.IconSportsHarness
  alias Icons.IconSportsHorseRacing
  alias Icons.IconSportsHorse
  alias Icons.IconSportsIceHockey
  alias Icons.IconSportsMma
  alias Icons.IconSportsMotorSports
  alias Icons.IconSportsPoker
  alias Icons.IconSportsPolitics
  alias Icons.IconSportsPool
  alias Icons.IconSportsPopular
  alias Icons.IconSportsRugby
  alias Icons.IconSportsSki
  alias Icons.IconSportsSnooker
  alias Icons.IconSportsSpecial
  alias Icons.IconSportsSquash
  alias Icons.IconSportsTableTennis
  alias Icons.IconSportsTennis
  alias Icons.IconSportsVolleyBall
  alias Icons.IconSportsWaterPolo
  alias Icons.IconStarEmpty
  alias Icons.IconStarFilled
  alias Icons.IconStarFlag
  alias Icons.IconStars
  alias Icons.IconStats
  alias Icons.IconStopwatch
  alias Icons.IconSuccessCircle
  alias Icons.IconSun
  alias Icons.IconSupport
  alias Icons.IconTable
  alias Icons.IconTag
  alias Icons.IconTelegram
  alias Icons.IconText
  alias Icons.IconTimer
  alias Icons.IconTwitter
  alias Icons.IconUpload
  alias Icons.IconUser
  alias Icons.IconUsers
  alias Icons.IconVerify
  alias Icons.IconVirtualSports
  alias Icons.IconVkontakte
  alias Icons.IconVolatility
  alias Icons.IconWalletRounded
  alias Icons.IconWallet
  alias Icons.IconWand
  alias Icons.IconWarning
  alias Icons.IconWhatsapp
  alias Icons.IconYoutube
  alias Icons.IconZoom

  def mount(params, _session, socket) do
    {:ok,
     assign(socket, theme_name: params["theme_name"] || "sportsbet-dark", active_page: __MODULE__)}
  end

  def render(assigns) do
    ~H"""
    <Inline>
      <IconAbout />
      <IconAdd />
      <IconAlertCircle />
      <IconAlignLeft />
      <IconAllSports />
      <IconArrowDiagonalDownLeft />
      <IconArrowDiagonalUpRight />
      <IconArrowDiagonals />
      <IconArrowDown />
      <IconArrowLDown />
      <IconArrowLUp />
      <IconArrowLeftRight />
      <IconArrowLeft />
      <IconArrowRight />
      <IconArrowTopRight />
      <IconArrowUpDown />
      <IconArrowUp />
      <IconAsianView />
      <IconAttache />
      <IconAward />
      <IconBannerInfo />
      <IconBell />
      <IconBitcoinTalk />
      <IconBombayClub />
      <IconBurger />
      <IconCalendarEmpty />
      <IconCalendar />
      <IconCard />
      <IconCase />
      <IconCashOut />
      <IconCasinoBell />
      <IconCasino />
      <IconChartArea />
      <IconChartBar />
      <IconChartPies />
      <IconChartRound />
      <IconChartSegment />
      <IconChevronDownRounded />
      <IconChevronDown />
      <IconChevronLeftRounded />
      <IconChevronLeft />
      <IconChevronRightRounded />
      <IconChevronRight />
      <IconChevronUpDown />
      <IconChevronUpRounded />
      <IconChevronUp />
      <IconCircle />
      <IconClaps />
      <IconClock />
      <IconCloseRounded />
      <IconCloseSmall />
      <IconClose />
      <IconCode />
      <IconCollapse />
      <IconCopy />
      <IconCredit />
      <IconCrypto />
      <IconCurrencyArs />
      <IconCurrencyBdt />
      <IconCurrencyBob />
      <IconCurrencyBrl />
      <IconCurrencyBtc />
      <IconCurrencyCad />
      <IconCurrencyClp />
      <IconCurrencyCny />
      <IconCurrencyCrc />
      <IconCurrencyEth />
      <IconCurrencyEur />
      <IconCurrencyGel />
      <IconCurrencyHkd />
      <IconCurrencyIdr />
      <IconCurrencyInr />
      <IconCurrencyIqd />
      <IconCurrencyJpy />
      <IconCurrencyKrw />
      <IconCurrencyLtc />
      <IconCurrencyMxn />
      <IconCurrencyMyr />
      <IconCurrencyPen />
      <IconCurrencyPkr />
      <IconCurrencyRub />
      <IconCurrencySoc />
      <IconCurrencyThb />
      <IconCurrencyTrx />
      <IconCurrencyTry />
      <IconCurrencyUah />
      <IconCurrencyUsd />
      <IconCurrencyUsdt />
      <IconCurrencyVes />
      <IconCurrencyVnd />
      <IconCurrencyXrp />
      <IconCursor />
      <IconData />
      <IconDelete />
      <IconDesktop />
      <IconDetails />
      <IconDouble />
      <IconDownload />
      <IconDuotoneArrows />
      <IconDuotoneChat />
      <IconDuotoneCoins />
      <IconDuotoneMail />
      <IconESportsCallOfDuty />
      <IconESportsCounterStrike />
      <IconESportsDota2 />
      <IconESportsENba />
      <IconESportsESport />
      <IconESportsFootball />
      <IconESportsHearthstone />
      <IconESportsLeagueOfLegends />
      <IconESportsOverwatch />
      <IconESportsRainbow />
      <IconESportsRocketLeague />
      <IconESportsStarCraft />
      <IconEdit />
      <IconErrorCircle />
      <IconError />
      <IconExpand />
      <IconEyeClosed />
      <IconEye />
      <IconFacebook />
      <IconFilter />
      <IconForward />
      <IconFreebet />
      <IconFullScreen />
      <IconGamepad />
      <IconGeneralInfo />
      <IconGift />
      <IconGlasses />
      <IconGlobe />
      <IconGoogleAuth />
      <IconGoogle />
      <IconHamburger />
      <IconHelp />
      <IconHistory />
      <IconHome />
      <IconHub88 />
      <IconHyperlink />
      <IconInPlay />
      <IconInfoCircle />
      <IconInfo />
      <IconInstagram />
      <IconLeftArrowCurveRight />
      <IconLifeRing />
      <IconLightbulb />
      <IconLimit />
      <IconLine />
      <IconLink />
      <IconListNumbered />
      <IconLiveCasino />
      <IconLiveChat />
      <IconLiveStream />
      <IconLock />
      <IconLogin />
      <IconLogoPlain />
      <IconLogout />
      <IconLoyalty0 />
      <IconMail />
      <IconMenuHome />
      <IconMenu />
      <IconMinus />
      <IconMobile />
      <IconMoney />
      <IconMoneybag />
      <IconMoon />
      <IconMore />
      <IconNews />
      <IconNotificationUnread />
      <IconNotification />
      <IconPadlock />
      <IconPencil />
      <IconPhoto />
      <IconPicture />
      <IconPin />
      <IconPlay />
      <IconPlus />
      <IconPriceBoost />
      <IconPrint />
      <IconProfile />
      <IconPromotions />
      <IconRefresh />
      <IconRow />
      <IconSbShield />
      <IconSearch />
      <IconSettings />
      <IconShare />
      <IconSliders />
      <IconSlots />
      <IconSnackbarSuccess />
      <IconSportWidget />
      <IconSportsAmericanFootBall />
      <IconSportsBadminton />
      <IconSportsBaseBall />
      <IconSportsBasketBall />
      <IconSportsBiathlon />
      <IconSportsBoxing />
      <IconSportsCenter />
      <IconSportsCricket />
      <IconSportsCycling />
      <IconSportsDarts />
      <IconSportsESports />
      <IconSportsFantasy />
      <IconSportsFeatured />
      <IconSportsFootBall />
      <IconSportsGolf />
      <IconSportsGreyhound />
      <IconSportsHandBall />
      <IconSportsHarness />
      <IconSportsHorseRacing />
      <IconSportsHorse />
      <IconSportsIceHockey />
      <IconSportsMma />
      <IconSportsMotorSports />
      <IconSportsPoker />
      <IconSportsPolitics />
      <IconSportsPool />
      <IconSportsPopular />
      <IconSportsRugby />
      <IconSportsSki />
      <IconSportsSnooker />
      <IconSportsSpecial />
      <IconSportsSquash />
      <IconSportsTableTennis />
      <IconSportsTennis />
      <IconSportsVolleyBall />
      <IconSportsWaterPolo />
      <IconStarEmpty />
      <IconStarFilled />
      <IconStarFlag />
      <IconStars />
      <IconStats />
      <IconStopwatch />
      <IconSuccessCircle />
      <IconSun />
      <IconSupport />
      <IconTable />
      <IconTag />
      <IconTelegram />
      <IconText />
      <IconTimer />
      <IconTwitter />
      <IconUpload />
      <IconUser />
      <IconUsers />
      <IconVerify />
      <IconVirtualSports />
      <IconVkontakte />
      <IconVolatility />
      <IconWalletRounded />
      <IconWallet />
      <IconWand />
      <IconWarning />
      <IconWhatsapp />
      <IconYoutube />
      <IconZoom />
    </Inline>
    <#CodePreview>
      <Inline>
        <IconAbout />
        <IconAdd />
        <IconAlertCircle />
        <IconAlignLeft />
        <IconAllSports />
        <IconArrowDiagonalDownLeft />
        <IconArrowDiagonalUpRight />
        <IconArrowDiagonals />
        <IconArrowDown />
        <IconArrowLDown />
        <IconArrowLUp />
        <IconArrowLeftRight />
        <IconArrowLeft />
        <IconArrowRight />
        <IconArrowTopRight />
        <IconArrowUpDown />
        <IconArrowUp />
        <IconAsianView />
        <IconAttache />
        <IconAward />
        <IconBannerInfo />
        <IconBell />
        <IconBitcoinTalk />
        <IconBombayClub />
        <IconBurger />
        <IconCalendarEmpty />
        <IconCalendar />
        <IconCard />
        <IconCase />
        <IconCashOut />
        <IconCasinoBell />
        <IconCasino />
        <IconChartArea />
        <IconChartBar />
        <IconChartPies />
        <IconChartRound />
        <IconChartSegment />
        <IconChevronDownRounded />
        <IconChevronDown />
        <IconChevronLeftRounded />
        <IconChevronLeft />
        <IconChevronRightRounded />
        <IconChevronRight />
        <IconChevronUpDown />
        <IconChevronUpRounded />
        <IconChevronUp />
        <IconCircle />
        <IconClaps />
        <IconClock />
        <IconCloseRounded />
        <IconCloseSmall />
        <IconClose />
        <IconCode />
        <IconCollapse />
        <IconCopy />
        <IconCredit />
        <IconCrypto />
        <IconCurrencyArs />
        <IconCurrencyBdt />
        <IconCurrencyBob />
        <IconCurrencyBrl />
        <IconCurrencyBtc />
        <IconCurrencyCad />
        <IconCurrencyClp />
        <IconCurrencyCny />
        <IconCurrencyCrc />
        <IconCurrencyEth />
        <IconCurrencyEur />
        <IconCurrencyGel />
        <IconCurrencyHkd />
        <IconCurrencyIdr />
        <IconCurrencyInr />
        <IconCurrencyIqd />
        <IconCurrencyJpy />
        <IconCurrencyKrw />
        <IconCurrencyLtc />
        <IconCurrencyMxn />
        <IconCurrencyMyr />
        <IconCurrencyPen />
        <IconCurrencyPkr />
        <IconCurrencyRub />
        <IconCurrencySoc />
        <IconCurrencyThb />
        <IconCurrencyTrx />
        <IconCurrencyTry />
        <IconCurrencyUah />
        <IconCurrencyUsd />
        <IconCurrencyUsdt />
        <IconCurrencyVes />
        <IconCurrencyVnd />
        <IconCurrencyXrp />
        <IconCursor />
        <IconData />
        <IconDelete />
        <IconDesktop />
        <IconDetails />
        <IconDouble />
        <IconDownload />
        <IconDuotoneArrows />
        <IconDuotoneChat />
        <IconDuotoneCoins />
        <IconDuotoneMail />
        <IconESportsCallOfDuty />
        <IconESportsCounterStrike />
        <IconESportsDota2 />
        <IconESportsENba />
        <IconESportsESport />
        <IconESportsFootball />
        <IconESportsHearthstone />
        <IconESportsLeagueOfLegends />
        <IconESportsOverwatch />
        <IconESportsRainbow />
        <IconESportsRocketLeague />
        <IconESportsStarCraft />
        <IconEdit />
        <IconErrorCircle />
        <IconError />
        <IconExpand />
        <IconEyeClosed />
        <IconEye />
        <IconFacebook />
        <IconFilter />
        <IconForward />
        <IconFreebet />
        <IconFullScreen />
        <IconGamepad />
        <IconGeneralInfo />
        <IconGift />
        <IconGlasses />
        <IconGlobe />
        <IconGoogleAuth />
        <IconGoogle />
        <IconHamburger />
        <IconHelp />
        <IconHistory />
        <IconHome />
        <IconHub88 />
        <IconHyperlink />
        <IconInPlay />
        <IconInfoCircle />
        <IconInfo />
        <IconInstagram />
        <IconLeftArrowCurveRight />
        <IconLifeRing />
        <IconLightbulb />
        <IconLimit />
        <IconLine />
        <IconLink />
        <IconListNumbered />
        <IconLiveCasino />
        <IconLiveChat />
        <IconLiveStream />
        <IconLock />
        <IconLogin />
        <IconLogoPlain />
        <IconLogout />
        <IconLoyalty0 />
        <IconMail />
        <IconMenuHome />
        <IconMenu />
        <IconMinus />
        <IconMobile />
        <IconMoney />
        <IconMoneybag />
        <IconMoon />
        <IconMore />
        <IconNews />
        <IconNotificationUnread />
        <IconNotification />
        <IconPadlock />
        <IconPencil />
        <IconPhoto />
        <IconPicture />
        <IconPin />
        <IconPlay />
        <IconPlus />
        <IconPriceBoost />
        <IconPrint />
        <IconProfile />
        <IconPromotions />
        <IconRefresh />
        <IconRow />
        <IconSbShield />
        <IconSearch />
        <IconSettings />
        <IconShare />
        <IconSliders />
        <IconSlots />
        <IconSnackbarSuccess />
        <IconSportWidget />
        <IconSportsAmericanFootBall />
        <IconSportsBadminton />
        <IconSportsBaseBall />
        <IconSportsBasketBall />
        <IconSportsBiathlon />
        <IconSportsBoxing />
        <IconSportsCenter />
        <IconSportsCricket />
        <IconSportsCycling />
        <IconSportsDarts />
        <IconSportsESports />
        <IconSportsFantasy />
        <IconSportsFeatured />
        <IconSportsFootBall />
        <IconSportsGolf />
        <IconSportsGreyhound />
        <IconSportsHandBall />
        <IconSportsHarness />
        <IconSportsHorseRacing />
        <IconSportsHorse />
        <IconSportsIceHockey />
        <IconSportsMma />
        <IconSportsMotorSports />
        <IconSportsPoker />
        <IconSportsPolitics />
        <IconSportsPool />
        <IconSportsPopular />
        <IconSportsRugby />
        <IconSportsSki />
        <IconSportsSnooker />
        <IconSportsSpecial />
        <IconSportsSquash />
        <IconSportsTableTennis />
        <IconSportsTennis />
        <IconSportsVolleyBall />
        <IconSportsWaterPolo />
        <IconStarEmpty />
        <IconStarFilled />
        <IconStarFlag />
        <IconStars />
        <IconStats />
        <IconStopwatch />
        <IconSuccessCircle />
        <IconSun />
        <IconSupport />
        <IconTable />
        <IconTag />
        <IconTelegram />
        <IconText />
        <IconTimer />
        <IconTwitter />
        <IconUpload />
        <IconUser />
        <IconUsers />
        <IconVerify />
        <IconVirtualSports />
        <IconVkontakte />
        <IconVolatility />
        <IconWalletRounded />
        <IconWallet />
        <IconWand />
        <IconWarning />
        <IconWhatsapp />
        <IconYoutube />
        <IconZoom />
      </Inline>
    </#CodePreview>
    """
  end
end
