defmodule Moon.Helpers.Icons do
  @moduledoc false

  def list_all do
    ~w(
      arrows_boost
      arrows_bottom_left
      arrows_bottom_right
      arrows_chevron_down_double
      arrows_chevron_left_double
      arrows_chevron_right_double
      arrows_chevron_up_double
      arrows_diagonals_bltr
      arrows_diagonals_tlbr
      arrows_down
      arrows_forward
      arrows_left_curved
      arrows_left_short
      arrows_left
      arrows_refresh
      arrows_remove_boost
      arrows_reply
      arrows_right_curved
      arrows_right_short
      arrows_right
      arrows_top_left
      arrows_top_right
      arrows_transfer
      arrows_up
      arrows_update
      chart_area
      chart_bar_alternitive
      chart_bar_vertical
      chart_bar
      chart_dashboard
      chart_fin
      chart_line
      chart_pie_chart
      chart_relation
      chart_round
      chat_chat
      chat_comment_add
      chat_comment_bubble_alert
      chat_comment_bubble_question_mark
      chat_comment_bubble
      chat_comment_remove
      chat_comment_text
      chat_comment
      chat_double_bubble
      chat_stats_chat
      controls_chevron_down_small
      controls_chevron_down
      controls_chevron_left_small
      controls_chevron_left
      controls_chevron_right_small
      controls_chevron_right
      controls_chevron_up_small
      controls_chevron_up
      controls_clear
      controls_close_small
      controls_close
      controls_collapse
      controls_diagonals_insight
      controls_diagonals_outsight
      controls_expand_alt
      controls_expand
      controls_eye_crossed
      controls_eye
      controls_minus
      controls_plus
      controls_vertical_double_chevron
      devices_bluetooth
      devices_joystick
      devices_keyboard
      devices_mac
      devices_macbook_and_iphone
      devices_macbook
      devices_mouse
      devices_phone
      devices_smartphone
      devices_tv_box
      files_add
      files_case
      files_clipboard_text
      files_clipboard
      files_code
      files_copy
      files_delete
      files_draft
      files_export
      files_external_link
      files_file
      files_folder_closed
      files_folder_open_alternative
      files_folder_open
      files_folder_zip
      files_glasses
      files_import
      files_magazine
      files_print
      files_remove
      files_save
      files_scan
      files_share
      files_sticker
      files_stickers
      files_table
      files_text
      generic_about
      generic_alarm_round
      generic_alarm
      generic_amount_number
      generic_bet
      generic_betslip
      generic_block
      generic_bookmark
      generic_browser
      generic_burger_regular
      generic_burger_zig
      generic_check_alternative
      generic_check_rounded
      generic_close
      generic_delete
      generic_dislike
      generic_download
      generic_drag_handle
      generic_edit
      generic_globe
      generic_heart
      generic_help
      generic_home
      generic_idea
      generic_info_alternative
      generic_info
      generic_lightning_bolt
      generic_like
      generic_link
      generic_log_in
      generic_log_out
      generic_loyalty
      generic_mention
      generic_menu
      generic_minus
      generic_multi_bet
      generic_news
      generic_pending
      generic_picture
      generic_plus
      generic_search
      generic_settings
      generic_share_android
      generic_share_ios_big
      generic_share_ios
      generic_star
      generic_tag
      generic_ticket
      generic_trophy
      generic_upload
      generic_user
      generic_users
      mail_box
      mail_email_stats
      mail_envelope
      mail_filter_crossed
      mail_filter
      mail_flag
      mail_link
      mail_send
      maps_compas
      maps_location
      maps_map
      maps_marker
      maps_panorama
      maps_pin_add
      maps_pin_location
      maps_pin
      maps_world
      media_fast_back
      media_fast_forward
      media_gif
      media_headphones
      media_megaphone
      media_mice_alternative
      media_mice
      media_monitor
      media_music
      media_no_volume
      media_pause
      media_photo
      media_play
      media_soundwave
      media_stop
      media_tuner_alternative
      media_tuner
      media_video
      media_volume
      notifications_activity
      notifications_add_bell
      notifications_alert
      notifications_app
      notifications_bell_alarm
      notifications_bell_cross
      notifications_bell_ringing_alternative
      notifications_bell_ringing
      notifications_bell
      notifications_error
      notifications_notifications
      notifications_question_mark
      notifications_settings
      other_frame
      other_id
      other_lightning
      other_moon
      other_other
      other_plug
      other_rewards
      other_sad
      other_smile
      other_sun
      other_water
      other3_dots_horizontal
      other3_dots
      security_bet_incurance
      security_key
      security_lock
      security_magnet
      security_passport_alert
      security_passport
      security_qr_code
      security_security_attention
      security_shield_secured
      security_shield
      security_umbrella
      security_unlock
      security_verified_face
      security_verified
      shop_bag
      shop_basket
      shop_card
      shop_cart
      shop_crypto_coin
      shop_crypto
      shop_wallet
      shop_wireless_pay
      software_bug
      software_clear
      software_code
      software_cursor
      software_dashboard
      software_data
      software_download
      software_hand
      software_log_out
      software_login
      software_nut
      software_plate
      software_puzzle
      software_settings
      software_shutdown
      software_sorting
      software_wrench
      sport_american_football
      sport_badminton
      sport_baseball
      sport_basketball
      sport_beach_volley
      sport_beach_volleyball
      sport_bombay
      sport_boxing
      sport_c_s_g_o
      sport_casino
      sport_cricket
      sport_cross_country
      sport_cycling
      sport_darts
      sport_dota2
      sport_e_n_b_a
      sport_e_soccer
      sport_esport_generic
      sport_featured
      sport_field_hockey
      sport_floorball
      sport_formula1
      sport_futsal
      sport_golf
      sport_greyhound
      sport_handball
      sport_harness
      sport_horse_racing
      sport_ice_hockey
      sport_lo_l
      sport_m_m_a
      sport_motor
      sport_overwatch
      sport_rugby
      sport_set_tennis
      sport_snooker
      sport_soccer
      sport_special_sports
      sport_specials
      sport_sportsbet
      sport_table_tennis
      sport_tennis
      sport_volleyball
      sport_waterpolo
      text_ancor
      text_attach
      text_bold
      text_bullets_list
      text_cards
      text_center
      text_clear_formatting
      text_cut
      text_descrease_indent
      text_hashtag
      text_incert_line
      text_increase_indent
      text_italic
      text_left_align
      text_list_view
      text_marker
      text_math
      text_numbers_list
      text_right_align
      text_size
      text_strikethrough
      text_style
      text_table_alternative
      text_table
      text_underline
      time_alarm
      time_calendar_add
      time_calendar_alternative
      time_calendar_date
      time_calendar_remove
      time_calendar_sucsess
      time_calendar
      time_clock
      time_sandglass
      time_stopwatch_timer
      time_stopwatch
      time_time
      time_watch
      travel_airplane_down
      travel_airplane_up
      travel_airplane
      travel_beach_chair
      travel_bed
      travel_bill
      travel_hotel
      travel_luggage
      travel_meal
      travel_passport
      travel_plug
      travel_rest
      travel_room
      travel_seats
      travel_suitcase
      travel_swimming_pool
      travel_wi_fi
      type_closed_hand
      type_default
      type_drag
      type_hand_pointing
      type_help
      type_move
      type_not_allowed
      type_opened_hand
      type_text
      type_zoom_in
      type_zoom_out
    )
  end

  def list_arrows do
    ~w(
      arrows_boost
      arrows_bottom_left
      arrows_bottom_right
      arrows_chevron_down_double
      arrows_chevron_left_double
      arrows_chevron_right_double
      arrows_chevron_up_double
      arrows_diagonals_bltr
      arrows_diagonals_tlbr
      arrows_down
      arrows_forward
      arrows_left_curved
      arrows_left_short
      arrows_left
      arrows_refresh
      arrows_remove_boost
      arrows_reply
      arrows_right_curved
      arrows_right_short
      arrows_right
      arrows_top_left
      arrows_top_right
      arrows_transfer
      arrows_up
      arrows_update
    )
  end

  def list_chart do
    ~w(
      chart_area
      chart_bar_alternitive
      chart_bar_vertical
      chart_bar
      chart_dashboard
      chart_fin
      chart_line
      chart_pie_chart
      chart_relation
      chart_round
    )
  end

  def list_chat do
    ~w(
      chat_chat
      chat_comment_add
      chat_comment_bubble_alert
      chat_comment_bubble_question_mark
      chat_comment_bubble
      chat_comment_remove
      chat_comment_text
      chat_comment
      chat_double_bubble
      chat_stats_chat
    )
  end

  def list_controls do
    ~w(
      controls_chevron_down_small
      controls_chevron_down
      controls_chevron_left_small
      controls_chevron_left
      controls_chevron_right_small
      controls_chevron_right
      controls_chevron_up_small
      controls_chevron_up
      controls_clear
      controls_close_small
      controls_close
      controls_collapse
      controls_diagonals_insight
      controls_diagonals_outsight
      controls_expand_alt
      controls_expand
      controls_eye_crossed
      controls_eye
      controls_minus
      controls_plus
      controls_vertical_double_chevron
    )
  end

  def list_devices do
    ~w(
      devices_bluetooth
      devices_joystick
      devices_keyboard
      devices_mac
      devices_macbook_and_iphone
      devices_macbook
      devices_mouse
      devices_phone
      devices_smartphone
      devices_tv_box
    )
  end

  def list_files do
    ~w(
      files_add
      files_case
      files_clipboard_text
      files_clipboard
      files_code
      files_copy
      files_delete
      files_draft
      files_export
      files_external_link
      files_file
      files_folder_closed
      files_folder_open_alternative
      files_folder_open
      files_folder_zip
      files_glasses
      files_import
      files_magazine
      files_print
      files_remove
      files_save
      files_scan
      files_share
      files_sticker
      files_stickers
      files_table
      files_text
    )
  end

  def list_generic do
    ~w(
      generic_about
      generic_alarm_round
      generic_alarm
      generic_amount_number
      generic_bet
      generic_betslip
      generic_block
      generic_bookmark
      generic_browser
      generic_burger_regular
      generic_burger_zig
      generic_check_alternative
      generic_check_rounded
      generic_close
      generic_delete
      generic_dislike
      generic_download
      generic_drag_handle
      generic_edit
      generic_globe
      generic_heart
      generic_help
      generic_home
      generic_idea
      generic_info_alternative
      generic_info
      generic_lightning_bolt
      generic_like
      generic_link
      generic_log_in
      generic_log_out
      generic_loyalty
      generic_mention
      generic_menu
      generic_minus
      generic_multi_bet
      generic_news
      generic_pending
      generic_picture
      generic_plus
      generic_search
      generic_settings
      generic_share_android
      generic_share_ios_big
      generic_share_ios
      generic_star
      generic_tag
      generic_ticket
      generic_trophy
      generic_upload
      generic_user
      generic_users
    )
  end

  def list_mail do
    ~w(
      mail_box
      mail_email_stats
      mail_envelope
      mail_filter_crossed
      mail_filter
      mail_flag
      mail_link
      mail_send
    )
  end

  def list_maps do
    ~w(
      maps_compas
      maps_location
      maps_map
      maps_marker
      maps_panorama
      maps_pin_add
      maps_pin_location
      maps_pin
      maps_world
    )
  end

  def list_media do
    ~w(
      media_fast_back
      media_fast_forward
      media_gif
      media_headphones
      media_megaphone
      media_mice_alternative
      media_mice
      media_monitor
      media_music
      media_no_volume
      media_pause
      media_photo
      media_play
      media_soundwave
      media_stop
      media_tuner_alternative
      media_tuner
      media_video
      media_volume
    )
  end

  def list_notifications do
    ~w(
      notifications_activity
      notifications_add_bell
      notifications_alert
      notifications_app
      notifications_bell_alarm
      notifications_bell_cross
      notifications_bell_ringing_alternative
      notifications_bell_ringing
      notifications_bell
      notifications_error
      notifications_notifications
      notifications_question_mark
      notifications_settings
    )
  end

  def list_other do
    ~w(
      other_frame
      other_id
      other_lightning
      other_moon
      other_other
      other_plug
      other_rewards
      other_sad
      other_smile
      other_sun
      other_water
      other3_dots_horizontal
      other3_dots
    )
  end

  def list_security do
    ~w(
      security_bet_incurance
      security_key
      security_lock
      security_magnet
      security_passport_alert
      security_passport
      security_qr_code
      security_security_attention
      security_shield_secured
      security_shield
      security_umbrella
      security_unlock
      security_verified_face
      security_verified
    )
  end

  def list_shop do
    ~w(
      shop_bag
      shop_basket
      shop_card
      shop_cart
      shop_crypto_coin
      shop_crypto
      shop_wallet
      shop_wireless_pay
    )
  end

  def list_software do
    ~w(
      software_bug
      software_clear
      software_code
      software_cursor
      software_dashboard
      software_data
      software_download
      software_hand
      software_log_out
      software_login
      software_nut
      software_plate
      software_puzzle
      software_settings
      software_shutdown
      software_sorting
      software_wrench
    )
  end

  def list_sport do
    ~w(
      sport_american_football
      sport_badminton
      sport_baseball
      sport_basketball
      sport_beach_volley
      sport_beach_volleyball
      sport_bombay
      sport_boxing
      sport_c_s_g_o
      sport_casino
      sport_cricket
      sport_cross_country
      sport_cycling
      sport_darts
      sport_dota2
      sport_e_n_b_a
      sport_e_soccer
      sport_esport_generic
      sport_featured
      sport_field_hockey
      sport_floorball
      sport_formula1
      sport_futsal
      sport_golf
      sport_greyhound
      sport_handball
      sport_harness
      sport_horse_racing
      sport_ice_hockey
      sport_lo_l
      sport_m_m_a
      sport_motor
      sport_overwatch
      sport_rugby
      sport_set_tennis
      sport_snooker
      sport_soccer
      sport_special_sports
      sport_specials
      sport_sportsbet
      sport_table_tennis
      sport_tennis
      sport_volleyball
      sport_waterpolo
    )
  end

  def list_text do
    ~w(
      text_ancor
      text_attach
      text_bold
      text_bullets_list
      text_cards
      text_center
      text_clear_formatting
      text_cut
      text_descrease_indent
      text_hashtag
      text_incert_line
      text_increase_indent
      text_italic
      text_left_align
      text_list_view
      text_marker
      text_math
      text_numbers_list
      text_right_align
      text_size
      text_strikethrough
      text_style
      text_table_alternative
      text_table
      text_underline
    )
  end

  def list_time do
    ~w(
      time_alarm
      time_calendar_add
      time_calendar_alternative
      time_calendar_date
      time_calendar_remove
      time_calendar_sucsess
      time_calendar
      time_clock
      time_sandglass
      time_stopwatch_timer
      time_stopwatch
      time_time
      time_watch
    )
  end

  def list_travel do
    ~w(
      travel_airplane_down
      travel_airplane_up
      travel_airplane
      travel_beach_chair
      travel_bed
      travel_bill
      travel_hotel
      travel_luggage
      travel_meal
      travel_passport
      travel_plug
      travel_rest
      travel_room
      travel_seats
      travel_suitcase
      travel_swimming_pool
      travel_wi_fi
    )
  end

  def list_type do
    ~w(
      type_closed_hand
      type_default
      type_drag
      type_hand_pointing
      type_help
      type_move
      type_not_allowed
      type_opened_hand
      type_text
      type_zoom_in
      type_zoom_out
    )
  end
end
